# use trusty (14.04) instead of the default precise (12.04) - seams to require additionally the 'sudo: required' flag - otherwise the 12.04 is still started.
dist: trusty
sudo: required
language: node_js

node_js:
#    - "node"
    - "4.6"
#    - "5.7"
#    - "0.12"

before_script:
    #- sudo npm install - is automatically executed when install is missing
    # use this when running tests locally - npm run start-webdriver &
    - npm start &
    # wait for starting the express app/selenium server
    - sleep 5
    # check that the web app is running:
    - wget http://localhost:3000/authors || true
    # show the beginning of the file - the whole file is not displayed within TRAVIS (because line is too long?)
    - cat authors | cut -d'/' -f1
    - cat authors

#script:
#    #- export TEST_RUN_LOCAL=true && npm test
#    #- echo "Run the same tests as above, but using the remote browser."
#    - export TEST_RUN_LOCAL=false && npm test

addons:
  sauce_connect: true

env:
  global:
    - secure: "J5fP8iudrLS80PslivYfNiyQCgeWCV0wNaiWoMuKIni+LZU4qv4ME+ouBHtpHfva1tfkGiaWP2g4rpDFUbKkI0WGNIwky8xgIGFPeqHiaiRjpJcVwt1tc6fIHjRwKQiXxlW1t4eaoP2vd+Ft07GH+lDqruHtd8gLzj8PjgoU4zZaQQdqBtZYw4rrEmGqzGyIJxn4HPMX9GgOamisZSUKkBlib5OiUqSrnsye6D1WDeM20APMCOZ8D8eRp0H0TycALO0jPxzVZqzCxu6I46zoFMwoFsunt1213S4wpCCGqH4YBDMLeHOQnKYfpK/5mfSQ1SceSkKVcTkIEfX11aiWEzqXzRiVN/aqIXsY9hj+vwSUqlU7PJcTw4SBNYMRUGMF0isvB1IW938gtlntGLha2QJyJPdVlW2bpo23fLDWWXPuvaiBGdm8GfMMAy/kPS5ZmNhWhtAK5+vbeGVYvRNdx2doRHU3v8liwnICoye/LCEvO0al8oKSwCMUCA+ATmaNulkWP4y7otuCLu6lCaCeL0cQBuNcMfUiVOpr39PcYBjHtQpSpbrAbqPP2OWt1gAv2Ipe3tafIX56oUhaghVF6XdRj+HXZrdRiuuGYcB363eL7zJmDbI0jJ+dZ0/Rz08hM2AWIG6CJQH0NQBvsd9jrei4+UhOMpEwiF3HpJoCXTo="
    - secure: "B/iBn1AFUtpcWiZOZaZZE9l+uIBNiMuE57ICAURfoP1KBLKysS/8DtryCnN5WFVafDR3J6mZIQBsl09iVvCfSXdqs2oHH+IWNILN1AgNEee8r/if9Gc+lZhzTRjTR9KY1+EKoyP9Af+TKh9EXinL2ZKBl1VlyJM11dcsPaWpg/CsVFQiyYG66s9zjyR6qGTuXFs9996YrnVEYEUJU9xpeFdFvA3ITh8YEEfBQ4kjHPaQvqw1N9sEskHsdHu7qmk7yD3JClL+6IEHhFoq+vG1QRh8wF9WGd8AyT/otWSBvwvVqb3PgB17qel7VN2U/ljwsukmYZWy77mCU6DqZpSxUpxm96LFwOWq7XvQGxBNaV4i/sOLZX3mszW2hbsQD5B7DeJ0JEL3hJkIxQ5dIl2A+yL795bO7g6exEpvQDfsygtHreUtUwFhx7X6pitQcdaoeENKRwSihmUQHPHZ97Wq2OY+It+54gBD4rf0Kp6zDi0EQyXamT8zESrOzWYZNUbNjxdh+s/OAPA4AUmnAA4xGpA1EkKGHXMvwVAyLoaVP4W98AYbtqmpApoDg4/dlYtAMTLHTpFOCwc2tkFUFTgR1uv2qI+oxqBMPVeRzKXba7cqCq8lOftUwEGsjVFeottxL1d7W85lrJuFK+GfSMdIjAmZnVz6IkDBcV6HVVPe1ek="

# Use platform configurator https://docs.saucelabs.com/reference/platforms-configurator
# Get the names and versions from the node.js tab in the section "COPY CODE".
# Use underscore for spaces in platform and browser names - they are replaced inside js.
  matrix:
    - _BROWSER: "firefox"
      _PLATFORM: "Linux"
      _VERSION: "45.0"
    - _BROWSER: "firefox"
      _PLATFORM: "Windows_7"
      _VERSION: "48.0" 
      #_VERSION: "49.0" - test-spec fails
      #_VERSION: "50.0" - test-spec fails - interactively Angular JS is failing, too. The expected third item in the TODO list is not appearing. The fourth is appearing (but as third).
      #_VERSION: "beta" - aka "51.0" test-spec works
      #_VERSION: "dev" - test-spec works
    - _BROWSER: "chrome"
      _PLATFORM: "Windows_7"
      _VERSION: "54.0"
    # - _BROWSER: "internet_explorer"
      # _PLATFORM: "Windows_7"
      # _VERSION: "11.0"
    # - _BROWSER: "microsoftedge"
      # _PLATFORM: "Windows_10"
      # _VERSION: "13.10586"
