# use trusty (14.04) instead of the default precise (12.04) - seams to require additionally the 'sudo: required' flag - otherwise the 12.04 is still started.
dist: trusty
sudo: required
language: node_js

node_js:
#    - "node"
    - "4.4"
#    - "5.7"
#    - "0.12"

#before_install:
    # download and start selenium server - thought that it is not necessary, but without the website is not available within SauceLabs.
    # download selenium server - when updating the jar: adapt the SELENIUMVERSION in the test files, too.
    # Latest version: http://www.seleniumhq.org/download/
    #- curl -O https://selenium-release.storage.googleapis.com/2.50/selenium-server-standalone-2.50.1.jar
    # Download and install the chromedriver to be able to execute the browser tests locally
    # Latest version: https://sites.google.com/a/chromium.org/chromedriver/downloads
    #- curl https://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip > chromedriver_linux64.zip && unzip chromedriver_linux64.zip && sudo cp chromedriver /usr/local/bin && sudo chmod +rx chromedriver /usr/local/bin/chromedriver
    # start this before installation to let the server be up and ready without extra waiting time.
    #- java -jar selenium-server-standalone-2.50.1.jar -Dwebdriver.chrome.driver=./chromedriver &
    #- sleep 15 works only on Win7/chrome44 and Win7/ie11
    #- sleep 15


before_script:
    - ./node_modules/protractor/bin/webdriver-manager start &
    #- sudo npm install - is automatically executed when install is missing
    # node app.js is started in postinstall of npm install
    #- node app.js &
    - npm start &
    # TODO reduce time to wait for starting the express app
    - sleep 5
    # check that the web app is running:
    - wget http://localhost:3000/authors || true
    # show the beginning of the file - the whole file is not displayed within TRAVIS (because line is too long?)
    - cat authors | cut -d'/' -f1

#script:
#    #- export TEST_RUN_LOCAL=true && npm test
#    #- echo "Run the same tests as above, but using the remote browser."
#    - export TEST_RUN_LOCAL=false && npm test

addons:
  sauce_connect: true

env:
  global:
    - secure: "NQeqz/4Eq/M1H6YykiVhe8VMtAepZ7rcsElB1FH+51bMEA3vnxeuSLwBERbvu7ccKQiV0SBpZgTJAdqMQayelIXun0jgpN0AmSm+c664T+WuBGpPcuS8LZYuBmH+8nWhocuwOPZ2r3H+vZQaaPfwqlrQhNJRPMP33n54IXl6R6B/aYhBUAlbkx7v/vh1KLUQl1FUEnmfLBgE0xTihzlP2Y9NqEKMWmW8zA9xYw2QIzVuNedVyk7Bgdzxx8XYXcmqiYV95xnJEaO044UIBQCQi7hG+QNUyGKq+g3i3lXUJNG46gvPzjuHWeqBc3FnZ1QtPLdjAnVRH6pCXxoYiK4ThmTTx4iNLqTqbEDavo0Kw1JJrxyoEYRbqUbJ7k6Gk+lsLvrW2Kk17UdIJyLN4dLr9tmLfSQsTwERelM81eVU33XzfsEjRYawEbIEzkJevfpZwqCByGAQ/4S8yXhPi+4AE1LKcHqd2XsW6925FivxOGjArqtOksaal8q4yF5ECe0jXRTgIRkv5F4n5nPfjlEoZ3cCzuXYlnuNzyNkjjpAVDrE5MFkH7kWugeIgkpZG/cDDNYfHNhPywtxs2Bgql+nw1tKUARa0LnGfXqHBDJFo+GQoigeNflmKeQRbp5/d2OHbCKYWpV5gypITxn4hr6Ue3euj17dT44G/KRx+J0F7y4="
    - secure: "oTNUFig7tSy/FKxcOMSfE0ymsldVZIwiubgso99gJP3T20aesQm4iOrn539BZO6L7KQZc5haYYbmGsr4jEZ/ygjqv7QKfyH2EVvIqF4MM1DWI7qv+pZEpr1u9/TYsoFBrGitjd7ON0U2ZkdBAq6AkYP1yZKoft5jzUL1zaEemKHRS2u8DsC2nC/q8NGOBYscnmzrNcW5JZh3XJxQGQeYFpazt7+bh+0btE9T3bKdwU1LH1Fo3r7XciOKcVUpWwbwf0LtkxcCwyE/2Hht/pmtUlNo9rkj8oOAqD0/PS2hNXOghstYmfrVE8cqlMMs3HwoKfHJ1Jd5jto3emahZk/32i+s3lQi8H1TSv+k0WRLtFJSmm0WQh57WfAGC8gntaa1Em5bAp+RoKQ5LGVY2iOhJ42lYpAMTxwqpcwf/w5Ox21COgaGngSuPbH+KFsdOc601LqLQFbJHR59ccJe4qDqdQRCpm17L4EgA40JIaDYDF7OHLVSuw4JZkFBibBXCWj6vOIdhjdH1qFJD2SFGYO8q1LJ053zCsZzrX5TnP5xWuTiL62azwhQXXhxJjZ4LJTMb3j/ETtkritbt/0c2ottEa+3r5/Bd5U4AATo35LZ0bOfZbCw5g5XuM67R14nTZbJKvSXDOZvpVP9PTBQUVS4CxWm84TD7JVQIBco/v1MorA="
# Use platform configurator https://docs.saucelabs.com/reference/platforms-configurator
# Get the names and versions from the node.js tab in the section "COPY CODE".
# Use underscore for spaces in platform and browser names - they are replaced inside js.
  matrix:
#    - _BROWSER: "firefox"
#      _PLATFORM: "Linux"
#      _VERSION: "44.0"
    - _BROWSER: "firefox"
      _PLATFORM: "Windows_7"
      _VERSION: "44.0"
#    - _BROWSER: "chrome"
#      _PLATFORM: "Windows_7"
#      _VERSION: "48.0"
#    - _BROWSER: "internet_explorer"
#      _PLATFORM: "Windows_7"
#      _VERSION: "11.0"
#    - _BROWSER: "microsoftedge"
#      _PLATFORM: "Windows_10"
#      _VERSION: "20.10240"
